/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#00164e",
        "on-tertiary-container": "#82abff",
        "tertiary-container": "#003d88",
        "inverse-surface": "#2d3133",
        "primary-fixed": "#dce1ff",
        "on-surface": "#191c1e",
        "surface-dim": "#d8dadc",
        "surface-container-highest": "#e0e3e5",
        "surface": "#f7f9fb",
        "on-background": "#191c1e",
        "on-surface-variant": "#444651",
        "on-tertiary-fixed-variant": "#004395",
        "primary-container": "#1e3a8a",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#adc6ff",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#131b2e",
        "primary": "#00236f",
        "secondary": "#565e74",
        "error-container": "#ffdad6",
        "background": "#f7f9fb",
        "outline-variant": "#c5c5d3",
        "on-secondary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "secondary-fixed": "#dae2fd",
        "primary-fixed-dim": "#b6c4ff",
        "tertiary-fixed": "#d8e2ff",
        "inverse-primary": "#b6c4ff",
        "secondary-container": "#dae2fd",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#001a42",
        "surface-container": "#eceef0",
        "on-secondary-fixed-variant": "#3f465c",
        "on-primary-container": "#90a8ff",
        "outline": "#757682",
        "surface-container-high": "#e6e8ea",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-container": "#5c647a",
        "surface-tint": "#4059aa",
        "surface-container-low": "#f2f4f6",
        "inverse-on-surface": "#eff1f3",
        "tertiary": "#00285e",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#bec6e0",
        "surface-bright": "#f7f9fb",
        "on-primary-fixed-variant": "#264191"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-desktop": "2rem",
        "sidebar-width-expanded": "16rem",
        "space-2xs": "0.25rem",
        "bottom-nav-height": "4rem",
        "space-sm": "0.75rem",
        "space-xs": "0.5rem",
        "gutter-tablet": "1.5rem",
        "space-md": "1rem",
        "space-2xl": "3rem",
        "gutter-mobile": "1rem",
        "sidebar-width-collapsed": "4.5rem",
        "space-xl": "2rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "numeric-table": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "numeric-table": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
