-- V1__init_schema.sql (H2 Dialect)

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone VARCHAR(50),
    role VARCHAR(50) NOT NULL,
    avatar_url VARCHAR(500),
    department VARCHAR(100),
    block_assigned VARCHAR(100),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR(50) NOT NULL,
    wing VARCHAR(50) NOT NULL,
    floor INT NOT NULL,
    room_type VARCHAR(50) NOT NULL,
    capacity INT NOT NULL DEFAULT 3,
    occupied_beds INT NOT NULL DEFAULT 0,
    monthly_rent DECIMAL(10, 2) NOT NULL DEFAULT 1200.00,
    status VARCHAR(50) NOT NULL DEFAULT 'AVAILABLE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_rooms_number_wing UNIQUE (room_number, wing)
);

CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE,
    roll_number VARCHAR(100) NOT NULL UNIQUE,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    room_id BIGINT NULL,
    bed_number VARCHAR(20),
    department VARCHAR(100) NOT NULL,
    academic_year VARCHAR(50) NOT NULL,
    guardian_name VARCHAR(150),
    guardian_phone VARCHAR(50),
    attendance_rate DECIMAL(5, 2) NOT NULL DEFAULT 100.00,
    fee_status VARCHAR(50) NOT NULL DEFAULT 'PAID',
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    avatar_url VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_students_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT FK_students_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE SET NULL
);

CREATE TABLE attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    record_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PRESENT',
    check_in_time VARCHAR(50),
    remarks VARCHAR(500),
    marked_by_user_id BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_attendance_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT FK_attendance_marked_by FOREIGN KEY (marked_by_user_id) REFERENCES users(id),
    CONSTRAINT UQ_student_attendance_date UNIQUE (student_id, record_date)
);

CREATE TABLE complaints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number VARCHAR(50) NOT NULL UNIQUE,
    student_id BIGINT NOT NULL,
    room_id BIGINT NULL,
    title VARCHAR(255) NOT NULL,
    description CLOB NOT NULL,
    category VARCHAR(100) NOT NULL,
    priority VARCHAR(50) NOT NULL DEFAULT 'MEDIUM',
    status VARCHAR(50) NOT NULL DEFAULT 'OPEN',
    assigned_staff VARCHAR(150),
    resolution_notes CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP NULL,
    CONSTRAINT FK_complaints_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT FK_complaints_room FOREIGN KEY (room_id) REFERENCES rooms(id)
);

CREATE TABLE fee_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR(50) NOT NULL UNIQUE,
    student_id BIGINT NOT NULL,
    fee_type VARCHAR(100) NOT NULL,
    term_name VARCHAR(100) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    due_date DATE NOT NULL,
    paid_date DATE NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    transaction_ref VARCHAR(100),
    payment_mode VARCHAR(50),
    notes VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_fee_invoices_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);

CREATE INDEX IX_users_username ON users(username);
CREATE INDEX IX_students_roll ON students(roll_number);
CREATE INDEX IX_rooms_wing_floor ON rooms(wing, floor);
CREATE INDEX IX_attendance_date ON attendance_records(record_date);
CREATE INDEX IX_complaints_status ON complaints(status);
CREATE INDEX IX_fee_invoices_status ON fee_invoices(status);
